### PR TITLE
fix(data-row-edit): check for empty file value

### LINKED ISSUE #28: Cannot save empty file
### How to Reproduce
Try to save an entity with empty value for a file attribute

### Expected behavior
The entity gets saved

### Observed behavior
Error message about how the empty file is missing a name attribute

### PR DESCRIPTION
**Pull request by fdlk**
fix #28

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- User documentation updated
- [x] Conventional commits (squash if needed)
- [x] No warnings during install
- Updated javascript typing

### CODE REVIEW

File: packages/data-row-edit/src/repository/dataRowRepository.js [hunk 1]
```diff
@@ -17,10 +17,7 @@ const buildFormData = (data, fields) => {
   const formData = new FormData()
   Object.entries(data).forEach((pair) => {
     const [key, value] = pair
-    const isFile = fields.find((field) => {
-      return field.id === key && field.type === 'file' && typeof value !==
-        'string'
-    })
+    const isFile = value && fields.find((field) => field.id === key && field.type === 'file' && typeof value !== 'string')
```
Comment (connoratrug) [inline packages/data-row-edit/src/repository/dataRowRepository.js]: update ( or add if missing) unit test

Comment (fdlk) [reply packages/data-row-edit/src/repository/dataRowRepository.js]: Yes, still working on this one
