### PR TITLE
fix(security): fixes #352 - console errors

### LINKED ISSUE #352: Console errors in Security manager
### How to Reproduce
Log in als een niet admin user. 

### Expected behavior
Geen errors in de console

### Observed behavior
http 401 error op
"/api/data/sys_sec_Role?expand=includes&q=name==ANONYMOUS,name==USER"

### PR DESCRIPTION
**Pull request by MaxPostema**
closes: #352

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
-  User documentation updated
- [x] Conventional commits (squash if needed)
-  No warnings during install
-  Updated javascript typing

### CODE REVIEW

File: packages/security/src/store/getters.ts [hunk 1]
```diff
@@ -46,6 +46,15 @@ const getters = {
       }
     }
     return ''
+  },
+  hasSuperUserRights: (state: SecurityModel, getters: any): boolean => {
```
Comment (connoratrug) [inline packages/security/src/store/getters.ts:50]: nice, maybe we should add these to the ui-context getters

**Review by connoratrug — CHANGES_REQUESTED** [review]
Seems to have 2 sources of user rights now ( one in main store and one from context), one from main store should probably be removed in favour of  context ui source.

**Review by jelmerveen — APPROVED** [review]

**Review by connoratrug — APPROVED** [review]
