### PR TITLE
fix(data-explorer): Fix selecting items with non standerd id / label

### LINKED ISSUE #463: Clipboard view does not use metadata label to show fields
### How to Reproduce
Create a entity that does not have a name property , and set the label property to some other field
for example 
```
Person {
  id: 1,
  FirstName: 'John'
}
```

set label prop to 'FirstName'

Use the entitySettings to set the 'isShop' property to 'true' and use the data-explorer 2 to select a few rows 
No go to the clipboard-view / view cart

### Expected behavior
The clipboard view show the selected rows the a id and label columns ( firstName in this example)

### Observed behavior
The label column is not shown

### PR DESCRIPTION
**Pull request by connoratrug**
fix(data-explorer): Fix selecting items with non standerd id / label

- Use metadata to find id and label columns
- Move finding id, and label and building clipboards items to getters for reuse

This closes #463, #462 

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- User documentation updated
- [x] Conventional commits (squash if needed)
- [x] No warnings during install
- [x] Updated javascript typing

### CODE REVIEW

**Comment by connoratrug** [comment]
[Fix clipboard view](https://trello.com/c/DzIKHWPH/348-fix-clipboard-view)

File: packages/data-explorer/src/store/getters.ts [hunk 1]
```diff
@@ -17,5 +18,31 @@ export default {
...
   hasEditSettingsRights: (state: ApplicationState, getters: any): boolean => {
     return getters.isUserAuthenticated && getters.userRoles.includes('ROLE_SU')
+  },
+  tableIdAttributeName: (state: ApplicationState): string | undefined => {
+    return state.tableMeta && state.tableMeta.idAttribute ? state.tableMeta.idAttribute.name : undefined
+  },
+  tableLabelAttributeName: (state: ApplicationState): string | undefined => {
+    return state.tableMeta && state.tableMeta.labelAttribute && state.tableMeta.labelAttribute.name ? state.tableMeta.labelAttribute.name : undefined
+  },
+  clipBoardItems: (state: ApplicationState, getters: any): ClipBoardItem[] => {
```
Comment (MaxPostema) [inline packages/data-explorer/src/store/getters.ts:28]: Plus point for making this into a getter

File: packages/data-explorer/tests/unit/store/getters.spec.ts [hunk 2]
```diff
@@ -98,4 +98,66 @@ describe('getters', () => {
...
+
+    it('should return undefined if not set', () => {
+      expect(getters.tableLabelAttributeName(state)).toEqual(undefined)
+    })
+
+    it('should return name of the label field if set', () => {
+      state = {
+        tableMeta: {
+          labelAttribute: {
+            name: 'some-label'
```
Comment (MaxPostema) [inline packages/data-explorer/tests/unit/store/getters.spec.ts:132]: Just a strange linting note:
Why is 'labelAttribute' on line 132 stretched over 3 lines, and line 150 and 159 with two properties on one line?

**Review by MaxPostema — APPROVED** [review]
